server:
  contextPath: /Tenfoot-Web
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: for
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: false
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 2
#    # Redis服务器地址
#    hostName: 121.41.117.81
##    hostName: localhost
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password: fmb_ServiceTest./
##    password:
#    pool:
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 20
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: 2
#      # 连接池中的最大空闲连接
#      max-idle: 20
#      # 连接池中的最小空闲连接
#      min-idle: 5
#    # 连接超时时间（毫秒）
#    timeout: 100000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/*/*Mapper.xml
  typeAliasesPackage: classpath:com.project.*
