spring:
  profiles:
    active: for
  devtools:
    restart:
      enabled: false
  cache:
    ehcache:
      config: classpath:config/ehcache.xml
#  redis:
#    # Redis服务器地址
#    host: 121.41.117.81
##    host: localhost
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password: fmb_ServiceTest./
##    password:
#    pool:
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 20
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: 2
#      # 连接池中的最大空闲连接
#      max-idle: 20
#      # 连接池中的最小空闲连接
#      min-idle: 5
#    # 连接超时时间（毫秒）
#    timeout: 100000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/*/*Mapper.xml
  typeAliasesPackage: classpath:com.project.domain.*
